package com.example.lab1.mybatis.dao;

import com.example.lab1.mybatis.model.Author;
import com.example.lab1.mybatis.model.Book;
import com.example.lab1.mybatis.model.Genre;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Tue Apr 11 20:50:40 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Tue Apr 11 20:50:40 EEST 2023
     */
    int insert(Book row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Tue Apr 11 20:50:40 EEST 2023
     */
    Book selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Tue Apr 11 20:50:40 EEST 2023
     */
    List<Book> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK
     *
     * @mbg.generated Tue Apr 11 20:50:40 EEST 2023
     */
    int updateByPrimaryKey(Book row);

    Author selectAuthor(Long id);

    List<Genre> selectGenresForBook(Long id);
}